name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm ci || npm install
      - run: npm run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [22, 24]
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci || npm install
      - run: npm test

  macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        node-version: [24]
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci || npm install
      - run: npm test
